public class exceptiontest {
    public static void main(String[] args)
{
//     try 
// {
//     System.out.println(1);
//     String s = null;
//     System.out.println(s);
//     System.out.println(s.length());
//     System.out.println(2); 
// }    
// catch (NullPointerException ex)
// {
//     System.out.println(4);
//     //System.out.println(s);
//     System.out.println(5);
// }
// System.out.println(6);

//System.out.println(test());
/*static int test()
{
    try{
        return 10;
    }
    catch(NumberFormatException ex)
    {
        return 20;
    }
    finally{
        return 30;
    }
*/

{
    /*try{
        System.out.println(1);
        int i = 10/0;
        System.out.println(2);
    }
    catch(ArithmeticException ex)
    {
        System.out.println(3);
        System.out.println(ex.getMessage());

        System.out.println(4);
    }
    System.out.println(5);
}*/
System.out.println(1);
try{
    System.out.println(1);
    String s = null;
    System.out.println()
}
}
}
